module.exports = {
  time: "time",
  count: "count",
  grid: "grid",
  pointer: "pointer",
  none: "none",
  block: "block",
  cell: ".cell",
  numberOfRowsString: "numberOfRowsString",
  numberOfColumnsString: "numberOfColumnsString",
  div: "div",
  board: "board",
  cellInitialColor: "cellInitialColor",
  restart: "restart",
  click: "click",
  default: "default",
  remove: "remove",
  add: "add",
  cellAndColor: "cell cellInitialColor",
  inputs: "inputs",
  changeSize: "changeSize",
  changeSizeText: "Change size",
  startGame: "startGame",
  capRestart: "Restart",
};
